### ISSUE TITLE
Live reload closes running electron instance

### ISSUE THREAD

**Issue by chrisesler** [Aluxian/electron-superkit#3]
Just downloaded repo, installed, ran gulp watch:darwin64. Electron launches fine, looks great. Made small change to html to see the livereload feature. The electron instance closes. Console outputs that the change was made and runs the watch task. But no errors.

**Comment by aluxian** [comment]
I will take a look tomorrow.

**Comment by aluxian** [comment]
Fixed in https://github.com/Aluxian/electron-superkit/commit/ca3272a166ee6c048a8eaea6f3fa3fa39829deaa
