### ISSUE TITLE
Browser cookies

### ISSUE THREAD

**Issue by vlados** [Aluxian/electron-superkit#4]
How I can enable browser's cookies?

**Comment by aluxian** [comment]
Hey @vlados, check this out: https://github.com/atom/electron/issues/1142

Let me know if that helps.

**Comment by aluxian** [comment]
This too: https://discuss.atom.io/t/how-to-manipulate-cookies-in-browserwindow/13537/2

**Comment by akovalyov** [comment]
@vlados you can also use electron `<webview>` tag.

**Comment by aluxian** [comment]
I checked again and indeed, [webview](https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md) has a `partition` attribute with which you can do session management.

**Comment by mmahalwy** [comment]
@Aluxian do you have an example? Struggling with this

**Comment by aluxian** [comment]
Be more specific, please. Example of what?

## 

Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Sat, Jan 23, 2016 at 3:05 am, Mohamed El Mahallawy < notifications@github.com [notifications@github.com] > wrote:
@Aluxian [https://github.com/Aluxian] do you have an example? Struggling with this

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/electron-superkit/issues/4#issuecomment-174101612] .[https://github.com/notifications/beacon/ABWmdqagWHhD0i66yA_I1JVGhbrcaOeVks5pcsk_gaJpZM4F9HvL.gif]
