### ISSUE TITLE
Sketch file is broken.

### ISSUE THREAD

**Issue by akovalyov** [Aluxian/electron-superkit#5]
`The document “design.sketch” could not be opened.`, Sketch 3.3.2

**Comment by aluxian** [comment]
I'm checking this right now.

**Comment by aluxian** [comment]
Mine opened, Sketch 3.3.2 (12043). Does this one work? https://infinit.io/_/FYej5XA

**Comment by akovalyov** [comment]
Hm, sorry. Reinstalled sketch and it worked successfully, sorry.
